name: Generate Swagger JSON

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate Swagger JSON
      run: npm run generate-swagger-ui

    - name: Upload Swagger JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: swagger-json
        path: ./swagger.json
